yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='comment'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .constants import MAX_CHAR_LIMIT
from .validators import validate_not_empty

User = get_user_model()


class Post(models.Model):
    """Модель публикации"""

    text = models.TextField(
        'Текст публикации',
        validators=[validate_not_empty],
        help_text='Введите текст вашей публикации',
    )
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор публикации',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Сообщество',
        help_text='Выберите сообщество для публикации',
    )
    image = models.ImageField(
        'Изображение',
        upload_to='posts/',
        blank=True,
        help_text='Загрузите изображение',
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:MAX_CHAR_LIMIT]


class Group(models.Model):
    """Модель сообществ сайта"""

    title = models.CharField('Название сообщества', max_length=200)
    slug = models.SlugField('Адрес страницы сообщества', unique=True)
    description = models.TextField('Описание сообщества')

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Модель комментариев"""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Публикация',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        'Текст комментария',
        validators=[validate_not_empty],
        help_text='Текст вашего комментария',
    )
    created = models.DateTimeField('Время комментария', auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.text[:MAX_CHAR_LIMIT]


class Follow(models.Model):
    """Модель подписок на авторов"""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписаться на',
    )

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_follow',
        )]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """Класс формы для заполнения публикации поста"""

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    """Форма заполнения комментария к посту"""

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import get_ten_posts_per_page


@cache_page(20, key_prefix='index_page')
def index(request):
    """Вью-функция главной страницы"""
    template = 'posts/index.html'
    post_list = Post.objects.select_related('group', 'author')
    context = {
        'page_obj': get_ten_posts_per_page(request, post_list),
    }

    return render(request, template, context)


def group_posts(request, slug):
    """Вью-функция страниц сообществ"""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('group', 'author')
    context = {
        'group': group,
        'page_obj': get_ten_posts_per_page(request, post_list),
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Вью-функция просмотра профиля пользователя с публикациями"""
    author = get_object_or_404(
        User.objects.select_related(),
        username=username,
    )
    post_list = author.posts.all()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author,
    ).exists()
    context = {
        'page_obj': get_ten_posts_per_page(request, post_list),
        'author': author,
        'following': following,
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Вью-функция просмотра отдельной публикации"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.select_related('post', 'author')
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=post.author,
    ).exists()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
        'following': following,
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Вью-функция страницы создания публикации"""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()

        return redirect('posts:profile', username=post.author)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Вью-функция изменения публикации"""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()

        return redirect('posts:post_detail', post_id=post_id)

    return render(
        request,
        'posts/create_post.html',
        {'is_edit': True, 'form': form, 'post': post},
    )


@login_required
def add_comment(request, post_id):
    """Вью-функция добавления комментария"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Вью-функция страницы с постами на подписки"""
    posts_list = Post.objects.filter(author__following__user=request.user)
    context = {
        'user': request.user,
        'page_obj': get_ten_posts_per_page(request, posts_list),
    }

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Вью функция для создания подписки"""
    author = get_object_or_404(User, username=username)
    if request.user == author or Follow.objects.filter(
        user=request.user,
        author=author,
    ).exists():

        return redirect('posts:profile', username=username)
    Follow.objects.create(user=request.user, author=author)

    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    """Вью функция для удаления подписки"""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()

    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} Редактировать запись 
  {% else %} 
    Новая публикация
  {% endif %} 
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %} Редактировать запись 
            {% else %}      
              Новая публикация   
            {% endif %}          
          </div>
          <div class="card-body"> 
            {% include 'includes/form_errors.html'%}
            <form method="post" {% if is_edit %} 
              action="{% url 'posts:post_edit' post_id=post.pk %}" 
              {% else %} action="{% url 'posts:post_create' %}" {% endif %}
              enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              {% include 'includes/field_form.html'%}
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %} Сохранить 
                {% else %} 
                  Добавить
                {% endif %}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock%}

yatube/templates/posts/field_form_post.html
{% load user_filters %}
{% for field in form %}     
    <div class="form-group row my-3 p-3">
        <label for="{{ field.id_for_label }}">
            {{ field.label }}
            {% if field.field.required %}
                <span class="required text-danger">*</span>
            {% endif %}
        </label>
        {{ field|addclass:'form-control' }} 
        {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" 
            class="form-text text-muted"
            >
            {{ field.help_text|safe }}
            </small>
        {% endif %}
    </div>
{% endfor %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Лента публикаций авторов, на которых вы подписались
{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>Лента публикаций авторов, на которых вы подписались</h1>
    {% include 'posts/includes/switcher.html' %}
    {% include 'posts/includes/paginator.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post.html' %}
    {% endfor %}
    <br>
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock%}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">     
  <h1>{{ group.title }}</h1>
  <p> {{ group.description }} </p>
  <h5>Всего публикаций сообщества: {{ group.posts.count }} </h5>
  <br>
  {% include 'posts/includes/paginator.html' %}
  {% for post in page_obj %}
  
    {% include 'posts/includes/post.html' %}
  {% endfor %} 
  <br>
    {% include 'posts/includes/paginator.html' %}
  <br>
  <a href="{% url 'posts:index' %}">Назад на главную страницу</a>
  </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>Последние обновления на сайте <span style="color:red">Ya</span>tube</h1>
    {% include 'posts/includes/switcher.html' %}
    {% include 'posts/includes/paginator.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post.html' %}
    {% endfor %}
    <br>
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock%}

yatube/templates/posts/post.html
{% load thumbnail %}
<article>
    <ul>
        <li>
            Автор: {% if not author %} <a href="{% url 'posts:profile' post.author %}">
                   {{ post.author.get_full_name }}</a> {% else %} {{ post.author.get_full_name }}
                   {% endif %}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if not group and post.group %}   
            <li>        
                Сообщество: <a href="{% url 'posts:group_list' post.group.slug %}">
                            {{ post.group }}</a>
            </li>
        {% endif %} 
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <div class='wordbreak'>
        <p>{{ post.text|linebreaks }}</p>
    </div>
    <a  href="{% url 'posts:post_detail' post_id=post.pk  %}">Подробнее</a><br>
    {% if user == post.author %}
        <a href="{% url 'posts:post_edit' post_id=post.pk  %}">Редактировать</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
</article>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="container py-5">  
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Автор: <a href="{% url 'posts:profile' post.author %}">
                        {{ post.author.get_full_name }}</a>
                </li>
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if post.group %}   
                    <li class="list-group-item">        
                        Сообщество: <a href="{% url 'posts:group_list' post.group.slug %}">
                                    {{ post.group.title }}</a>
                    </li>
                {% endif %} 
                <li class="list-group-item">
                    Всего постов пользователя: {{ post.author.posts.count }}, <a href="{% url 'posts:profile' post.author  %}">читать</a>
                </li>
                <li class="list-group-item">   
                    Подписавшихся на автора: {{ post.author.following.count }}   
                </li>
                <li class="list-group-item">
                    {% if request.user != post.author %}      
                        {% if following %}
                        <a
                            class="btn btn-md btn-light"
                            href="{% url 'posts:profile_unfollow' post.author.username %}" role="button"
                        >
                            Отписаться
                        </a>
                        {% else %}
                            <a
                            class="btn btn-md btn-primary"
                            href="{% url 'posts:profile_follow' post.author.username %}" role="button"
                            >
                            Подписаться
                            </a>
                        {% endif %}
                    {% endif %}        
                  </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <div class='wordbreak'>
                <p>{{ post.text|linebreaks }}</p> 
            </div>
            {% if request.user == post.author %}
                <a href="{% url 'posts:post_edit' post_id=post.pk  %}">Редактировать</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
            <p><b> Комментарии:</b></p>
            {% include 'posts/includes/comments.html' %}
        </article>
    </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{author.get_full_name}}{% endblock %}
{% block content %}
  <div class="container py-5">        
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <h5>Все посты пользователя {{author.get_full_name}}</h5> 
          </li>
          <li class="list-group-item">   
            Всего постов: {{ author.posts.count }}   
          </li>
          <li class="list-group-item">   
            Подписавшихся на автора: {{ author.following.count }}   
          </li>
          <li class="list-group-item">   
            Подписался на других: {{ author.follower.count }}   
          </li>
          <li class="list-group-item">
            {% if request.user != author %}    
              {% if following %}
                <a
                  class="btn btn-md btn-light"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                  Отписаться
                </a>
              {% else %}
                  <a
                    class="btn btn-md btn-primary"
                    href="{% url 'posts:profile_follow' author.username %}" role="button"
                  >
                    Подписаться
                  </a>
              {% endif %}
            {% endif %}      
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% include 'posts/includes/paginator.html' %}
        {% for post in page_obj %}
          {% include 'posts/includes/post.html' %}
        {% endfor %}
        <br>
        {% include 'posts/includes/paginator.html' %}
      </article>
    </div>
  </div>
{% endblock %}